### ISSUE TITLE
Broken link to the Vessel GIF

### ISSUE THREAD

**Issue by feedmesource** [x2110311x/twentyonepilotswiki#18]
**Describe the error**
On "Vessel Gif changed" page of dmaorg,info there is broken link on "04/21/18 - Vessel gif discovered" chapter.
I mean the "Vessel gif" link.

**What should it be**
I think it should be link to the first mysterious hint of Dema (Vessel store GIF).

**Link to the page**
[link](https://www.twentyonepilots.wiki/docs/dmaorg/04-20-18-Vessel-gif-changed#042118---vessel-gif-discovered)

**Comment by x2110311x** [comment]
Good catch. Indeed the gif does seem to be gone. I’ll have to reupload and fix that link tonight.

thank you!!
